title: Michael Morrow
url: "https://michaelmorrow.org"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/morrowmh"
footer_text: "Find me on GitHub"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "/files/MichaelMorrow_CV.pdf"
 - name: "Extras"
   link: "extras"
 - name: "Contact"
   link: "contact"
